### ISSUE TITLE
Remove/unify variables in Constants.java/config.json

### ISSUE THREAD

**Issue by cjpark87** [cjpark87/rdt-scan#1]

**Comment by mariakakis** [comment]
Making notes on some that would be nice to remove:
INTENSITY_THRESHOLD?
LINE_SEARCH_WIDTH

**Comment by atm15** [comment]
Would also be nice to have a nested structure so that people can do multiple fiducials, but that will be a lot of work for later (don't want to make it an issue right now)

**Comment by hungngo97** [comment]
So now the Constants.java file should read the values from config.json?
