### ISSUE TITLE
Blood detection

### ISSUE THREAD

**Issue by cjpark87** [cjpark87/rdt-scan#4]

**Comment by hungngo97** [comment]
This sounds interesting :)

**Comment by cjpark87** [comment]
You can take this one. It should be done during interpretation, not during capturing.

**Comment by hungngo97** [comment]
Can you describe a bit more on what and where the blood is shown? An example image would be great

**Comment by cjpark87** [comment]
@hungngo97 Could you also add "isBlood" field in RDTInterpretationResult Class?
