### ISSUE TITLE
Update interpretation to the current python verion

### ISSUE THREAD

**Issue by cjpark87** [cjpark87/rdt-scan#5]

**Comment by hungngo97** [comment]
May i ask what Python version? We are not using Python in the app though right?

**Comment by hungngo97** [comment]
Do you mean updating the python script version that I had to follow the current Android app?

**Comment by cjpark87** [comment]
Yep yep. Update the android code so that it will sync up with the python interpretation code

**Comment by cjpark87** [comment]
It might be already synced with python interpretation code. will need to double check
